security:
    encoders:
        Sample\AdminBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: SampleAdminBundle:User }

    firewalls:
        login_firewall:
            pattern:    ^/admin/login$
            anonymous:  ~
        admin_area:
            pattern:    ^/admin
            #http_basic: ~
            anonymous: ~
            form_login:
                login_path:  /admin/login
                check_path:  /admin/login_check

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

