security:
    encoders:
        Sample\AdminBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        admin:
            entity:
                class: Sample\AdminBundle\Entity\User
                property: username

    firewalls:
        # 管理者エリアのログイン画面のみセキュリティを無効に設定
        admin_area_login:
            pattern:  ^/admin/login
            security: false
        admin_area:
            provider:   admin
            pattern:    ^/admin
            #http_basic: ~
            form_login:
                login_path:  /admin/login
                check_path:  /admin/login_check

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

