parameters:
#    sample_contact.example.class: Sample\ContactBundle\Example

services:
#    sample_contact.example:
#        class: %sample_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
